package com.roger.conceptos4.bases_de_datos;

import java.sql.*;

public class InicioBD {
    public static void main(String[] args) throws SQLException {

        Connection conexionBaseDatos =ConectarBaseDatos.getConexionBaseDatos();

        Statement sentenciaSql = conexionBaseDatos.createStatement();
        sentenciaSql.execute("CREATE TABLE usuarios(id INT PRIMARY KEY, nombre VARCHAR(100))");
        sentenciaSql.execute("INSERT INTO usuarios VALUES(1, 'Juan')");
        sentenciaSql.execute("INSERT INTO usuarios VALUES(2, 'Pedro')");
        sentenciaSql.execute("INSERT INTO usuarios VALUES(3, 'Sandra')");


        // Crear tabla
        String createTableSQL = " CREATE TABLE FACULTAD ( " +
                " id_facultad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                " nombre VARCHAR(50) NOT NULL, " +
                " decano VARCHAR(50) NOT NULL )";

        sentenciaSql.execute(createTableSQL);

        sentenciaSql.execute("INSERT INTO FACULTAD VALUES(1, 'Ciencias Humanas', 'Fernando Campos Polo')");
        sentenciaSql.execute("INSERT INTO FACULTAD VALUES(2, 'Ciencias Básicas e Ingeniería','Elvis Miguel Pérez Rodríguez')");
        sentenciaSql.execute("INSERT INTO FACULTAD VALUES(3, 'Ciencias de la Salud','Luz Miryam Tobón Borrero')");


        InicioBD.consultar(sentenciaSql);


        sentenciaSql.execute("delete from usuarios where id=1");
        sentenciaSql.execute("delete from facultad where id_facultad = 1");

        sentenciaSql.execute("update facultad set nombre = 'FCBI' ");

        InicioBD.insertarConRestriciones(sentenciaSql);
        InicioBD.consultar(sentenciaSql);
        InicioBD.consultarConRestricciones(sentenciaSql);

        conexionBaseDatos.close();

    }

    public static void consultar(Statement sentenciaSql ) throws SQLException {
        System.out.println("consultando tabla usuarios");
        ResultSet rs = sentenciaSql.executeQuery("SELECT * FROM usuarios");
        while (rs.next()) {
            System.out.println(rs.getInt("id") + ": " + rs.getString("nombre"));
        }

        System.out.println("consultando tabla facultad");
        rs = sentenciaSql.executeQuery("SELECT * FROM facultad");
        while (rs.next()) {
            System.out.println(rs.getInt("id_facultad") + ": " + rs.getString("nombre") + " " + rs.getString("decano")  );
        }

    }


    public static void consultarConRestricciones(Statement sentenciaSql ) throws SQLException
    {
        String sql="SELECT * FROM facultad where id_facultad=? ";
        PreparedStatement restriccionSql = sentenciaSql.getConnection().prepareStatement(sql);
        restriccionSql.setInt(1, 2);
        System.out.println("consultando tabla facultad");
        ResultSet rs = restriccionSql.executeQuery();
        while (rs.next()) {
            System.out.println(rs.getInt("id_facultad") + ": " + rs.getString("nombre") +
                    " " + rs.getString("decano")  );
        }

    }
    public static void insertarConRestriciones(Statement sentenciaSql) throws SQLException {


        String sql = "INSERT INTO facultad (id_facultad, nombre, decano) VALUES (?, ?, ?)";

        PreparedStatement restriccionSql = sentenciaSql.getConnection().prepareStatement(sql);
        restriccionSql.setInt(1, 4);
        restriccionSql.setString(2, "Ciencias Agrícolas");
        restriccionSql.setString(3, "Cristobal Lugo");
        restriccionSql.executeUpdate();

        restriccionSql.setInt(1, 5);
        restriccionSql.setString(2, "Ciencias Económicas");
        restriccionSql.setString(3, "Juan Romero");
        restriccionSql.executeUpdate();

    }
}
